DROP TABLE XFUEL;

CREATE TABLE XFUEL (
    ID          INTEGER      PRIMARY KEY AUTOINCREMENT,
    DATE_REG    DATETIME     DEFAULT (DATE('now')),
    TIME_REG    DATETIME     DEFAULT (TIME('now')),
    TYPE        VARCHAR (10) NOT NULL,
    LOCATION    VARCHAR (10) NOT NULL,
    REASON      VARCHAR (10) NOT NULL,
    START       DATETIME     NOT NULL,
    PLANNED_END DATETIME     NOT NULL,
    REAL_END    DATETIME,
    REMARK      TEXT,
    CREATE_USER VARCHAR (40) NOT NULL,
    CHANGE_USER VARCHAR (40) NOT NULL
);

INSERT INTO XFUEL (TYPE, LOCATION, REASON, START, PLANNED_END, REAL_END, REMARK, CREATE_USER, CHANGE_USER)
VALUES ('AIRPORT', 'VCP', 'WXX', '06/04/2020 09:47', '06/04/2020 09:47', 0, 'TESTE TESTE', 'EU', 'EU');


SELECT TYPE, LOCATION, REASON, CREATE_USER FROM XFUEL WHERE DATE_REG = DATE('NOW');


select * from xfuel;
